services:
  squad-postgres:
    image: postgres:16.0-alpine3.17
    container_name: "${APP_DB_POSTGRES_CONTAINER_NAME:-squad-store-postgres-db}"
    environment:
      POSTGRES_USER: "${APP_DB_POSTGRES_USER:-postgresuser}"
      POSTGRES_PASSWORD: "${APP_DB_POSTGRES_PASSWORD:-postgresspass1234}"
      POSTGRES_DB: "${APP_DB_POSTGRES_DB:-orig_schema}"
    ports:
      - "${APP_DB_POSTGRES_HOST_PORT:-5432}:${APP_DB_POSTGRES_CONTAINER_PORT:-5432}"
    expose:
      - ${APP_DB_POSTGRES_CONTAINER_PORT:-5432}
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db/seed/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build:
      context: .
    env_file:
      - '.env'
    volumes:
      - .:/squad-app
    environment:
      NODE_ENV: production
      APP_PORT: ${APP_API_CONTAINER_PORT:-3000}
    ports:
      - "${APP_API_HOST_PORT:-8082}:${APP_API_CONTAINER_PORT:-3000}"
    container_name: "${APP_API_CONTAINER_NAME:-squad-store-service-api}"


